# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - mvcgithubactions

on:
  push:
    branches:
      - master

jobs:
  githubActions_Testes:
    name: Testes GitHubActions.Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Executando Testes
      run: dotnet test GitHubActions.Tests/GitHubActions.Tests.csproj -v n    

  gitHubActions_Web:
    name: Build GitHubActions.Web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: 'GitHubActions.Web/'
    
    - name: Build
      run: dotnet build GitHubActions.Web --configuration Release --no-restore
      working-directory: 'GitHubActions.Web/'      
    
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: 'GitHubActions.Web/'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'mvcgithubactions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8fab95f6353948959785c75bbf55f95a }}
        package: ${{env.DOTNET_ROOT}}/myapp 